-- Drop and recreate web_ai.demographics with age fix

DROP MATERIALIZED VIEW IF EXISTS web_ai.demographics;

CREATE MATERIALIZED VIEW web_ai.demographics AS
WITH demographics AS (
    SELECT
        dim_contact_level_details.property_name,
        dim_contact_level_details.site_id_property_unit_number,
        dim_contact_level_details.resident_member_id,
        dim_contact_level_details.unit_number,
        dim_contact_level_details.current_employment_additional_annual_income,
        dim_contact_level_details.current_employment_address,
        dim_contact_level_details.current_employment_estimated_annual_income,
        dim_contact_level_details.current_employment_job_title,
        dim_contact_level_details.current_employment_job_type,
        dim_contact_level_details.current_employment_length_of_employment,
        dim_contact_level_details.current_employment_miles_to_work,
        dim_contact_level_details.current_employment_name,
        dim_contact_level_details.current_employment_start_date,
        -- Age fix: set age <= 0 or age > 100 to NULL
        CASE
            WHEN dim_contact_level_details.age BETWEEN 1 AND 100 THEN dim_contact_level_details.age
            ELSE NULL
        END AS age,
        dim_contact_level_details.citizenship,
        dim_contact_level_details.contact_primary_language,
        dim_contact_level_details.ethnicity,
        dim_contact_level_details.gender,
        dim_contact_level_details.marital_status,
        dim_contact_level_details.co_signer,
        dim_contact_level_details.criminal_history,
        dim_contact_level_details.email,
        dim_contact_level_details.employee,
        dim_contact_level_details.first_name,
        dim_contact_level_details.middle_name,
        dim_contact_level_details.last_name,
        dim_contact_level_details.forwarding_address,
        dim_contact_level_details.guarantor,
        dim_contact_level_details.home_phone,
        dim_contact_level_details.lease_signer,
        dim_contact_level_details.length_of_stay,
        dim_contact_level_details.occupant,
        dim_contact_level_details.opt_in_for_email_notifications,
        dim_contact_level_details.relationship_household_status,
        dim_contact_level_details.resident_since,
        dim_contact_level_details.applied_date,
        dim_contact_level_details.contact_level_status,
        dim_contact_level_details.custom_payment_plan_name,
        dim_contact_level_details.household_language,
        dim_contact_level_details.household_name,
        dim_contact_level_details.lease_start_date,
        dim_contact_level_details.lease_end_date,
        dim_contact_level_details.lease_level_occupancy_status,
        dim_contact_level_details.ledger_balance,
        dim_contact_level_details.payment_plan_name,
        dim_contact_level_details.screening_current_historical,
        dim_contact_level_details.screening_decision,
        dim_contact_level_details.screening_submission_date,
        dim_contact_level_details.screening_decision_by,
        dim_contact_level_details.screening_decision_date,
        dim_contact_level_details.screening_override_decision,
        dim_contact_level_details.screening_override_decision_factors,
        dim_contact_level_details.other_previous_residence_address,
        dim_contact_level_details.other_previous_residence_length_of_residency,
        dim_contact_level_details.other_previous_residence_reason_for_leaving,
        dim_contact_level_details.other_previous_residence_rent_amount,
        dim_contact_level_details.other_previous_residence_rent_own_na,
        dim_contact_level_details.previous_employer_address,
        dim_contact_level_details.previous_employer_name,
        dim_contact_level_details.previous_employment_estimated_annual_income,
        dim_contact_level_details.previous_employment_job_title,
        dim_contact_level_details.previous_employment_job_type,
        dim_contact_level_details.previous_employment_length_of_employment,
        dim_contact_level_details.previous_residence_address,
        dim_contact_level_details.previous_residence_length_of_residency,
        dim_contact_level_details.previous_residence_reason_for_leaving,
        dim_contact_level_details.previous_residence_rent_amount,
        dim_contact_level_details.previous_residence_rent_own_na,
        dim_contact_level_details.previous_residence_residence_name,
        dim_contact_level_details.has_been_evicted,
        dim_contact_level_details.has_been_sued_for_property_damages,
        dim_contact_level_details.has_been_sued_for_rent,
        dim_contact_level_details.has_broken_lease
    FROM analytics.dim_contact_level_details
    WHERE dim_contact_level_details.age >= 0 OR dim_contact_level_details.age <= 95
),
dim_info_property AS (
    SELECT DISTINCT
        vw_bi_dim_info_property.property_number,
        vw_bi_dim_info_property.property_name,
        CASE
            WHEN vw_bi_dim_info_property.entity_id = 328 THEN '348-' || vw_bi_dim_info_property.property_name::text
            WHEN vw_bi_dim_info_property.entity_id = 142 THEN '143-' || vw_bi_dim_info_property.property_name::text
            WHEN vw_bi_dim_info_property.entity_id = 329 THEN '345-' || vw_bi_dim_info_property.property_name::text
            WHEN vw_bi_dim_info_property.entity_id = 351 THEN '369-' || vw_bi_dim_info_property.property_name::text
            ELSE (vw_bi_dim_info_property.property_number || '-') || vw_bi_dim_info_property.property_name::text
        END AS community,
        vw_bi_dim_info_property.regional_vp_sr_vp AS "Regional VP  | Sr. VP",
        vw_bi_dim_info_property.regional_area_manager,
        vw_bi_dim_info_property.investor
    FROM analytics.vw_bi_dim_info_property
)
SELECT
    dip.property_name,
    dmg.site_id_property_unit_number,
    dip.community,
    dip."Regional VP  | Sr. VP",
    dip.regional_area_manager,
    dip.investor,
    dmg.resident_member_id,
    dmg.unit_number,
    dmg.current_employment_additional_annual_income,
    dmg.current_employment_address,
    dmg.current_employment_estimated_annual_income,
    dmg.current_employment_job_title,
    dmg.current_employment_job_type,
    dmg.current_employment_length_of_employment,
    dmg.current_employment_miles_to_work,
    dmg.current_employment_name,
    dmg.current_employment_start_date,
    dmg.age,
    dmg.citizenship,
    dmg.contact_primary_language,
    dmg.ethnicity,
    dmg.gender,
    dmg.marital_status,
    dmg.co_signer,
    dmg.criminal_history,
    dmg.email,
    dmg.employee,
    dmg.first_name,
    dmg.middle_name,
    dmg.last_name,
    dmg.forwarding_address,
    dmg.guarantor,
    dmg.home_phone,
    dmg.lease_signer,
    dmg.length_of_stay,
    dmg.occupant,
    dmg.opt_in_for_email_notifications,
    dmg.relationship_household_status,
    dmg.resident_since,
    dmg.applied_date,
    dmg.contact_level_status,
    dmg.custom_payment_plan_name,
    dmg.household_language,
    dmg.household_name,
    dmg.lease_start_date,
    dmg.lease_end_date,
    dmg.lease_level_occupancy_status,
    dmg.ledger_balance,
    dmg.payment_plan_name,
    dmg.screening_current_historical,
    dmg.screening_decision,
    dmg.screening_submission_date,
    dmg.screening_decision_by,
    dmg.screening_decision_date,
    dmg.screening_override_decision,
    dmg.screening_override_decision_factors,
    dmg.other_previous_residence_address,
    dmg.other_previous_residence_length_of_residency,
    dmg.other_previous_residence_reason_for_leaving,
    dmg.other_previous_residence_rent_amount,
    dmg.other_previous_residence_rent_own_na,
    dmg.previous_employer_address,
    dmg.previous_employer_name,
    dmg.previous_employment_estimated_annual_income,
    dmg.previous_employment_job_title,
    dmg.previous_employment_job_type,
    dmg.previous_employment_length_of_employment,
    dmg.previous_residence_address,
    dmg.previous_residence_length_of_residency,
    dmg.previous_residence_reason_for_leaving,
    dmg.previous_residence_rent_amount,
    dmg.previous_residence_rent_own_na,
    dmg.previous_residence_residence_name,
    dmg.has_been_evicted,
    dmg.has_been_sued_for_property_damages,
    dmg.has_been_sued_for_rent,
    dmg.has_broken_lease
FROM dim_info_property dip
LEFT JOIN demographics dmg
    ON split_part(dmg.site_id_property_unit_number::text, '-', 2)::integer = dip.property_number;
