-- DROP PROCEDURE staging.sp_contact_level_details();

CREATE OR REPLACE PROCEDURE staging.sp_contact_level_details()
 LANGUAGE plpgsql
AS $procedure$
BEGIN
CREATE TEMP TABLE temp_contact_level_details (
	property_name varchar(100) NULL,
    site_id_property_unit_number varchar(100),
	resident_member_id int4 NOT NULL,
	unit_number varchar(1000) NULL,
	current_employment_additional_annual_income varchar(100) NULL,
	current_employment_address varchar(1000) NULL,
	current_employment_estimated_annual_income numeric(30,4) NULL,
	current_employment_job_title varchar(100) NULL,
	current_employment_job_type varchar(100) NULL,
	current_employment_length_of_employment varchar(100) NULL,
	current_employment_miles_to_work numeric(30,4) NULL,
	current_employment_name varchar(100) NULL,
	current_employment_start_date date NULL,
	age INT NULL,
	citizenship varchar(100) NULL,
	contact_primary_language varchar(100) NULL,
	ethnicity varchar(100) NULL,
	gender varchar(1000) NULL,
	marital_status varchar(100) NULL,
	co_signer varchar(100) NULL,
	criminal_history varchar(100) NULL,
	email varchar(100) NULL,
	employee varchar(100) NULL,
	first_name varchar(100) NULL,
	middle_name varchar(100) NULL,
	last_name varchar(100) NULL,
	forwarding_address varchar(1000) NULL,
	guarantor varchar(1000) NULL,
	home_phone varchar(1000) NULL,
	lease_signer varchar(1000) NULL,
	length_of_stay varchar(1000) NULL,
	occupant varchar(1000) NULL,
	opt_in_for_email_notifications varchar(1000) NULL,
	relationship_household_status varchar(1000) NULL,
	resident_since DATE NULL,
	applied_date DATE NULL,
	contact_level_status varchar(1000) NULL,
	custom_payment_plan_name varchar(1000) NULL,
	household_language varchar(1000) NULL,
	household_name varchar(1000) NULL,
	lease_start_date date NULL,
	lease_end_date date NULL,
	lease_level_occupancy_status varchar(1000) NULL,
	ledger_balance numeric(30,4) NULL,
	payment_plan_name varchar(1000) NULL,
	screening_current_historical varchar(1000) NULL,
	screening_decision varchar(1000) NULL,
	screening_submission_date date NULL,
	screening_decision_by varchar(1000) NULL,
	screening_decision_date date NULL,
	screening_override_decision varchar(1000) NULL,
	screening_override_decision_factors varchar(1000) NULL,
	other_previous_residence_address varchar(1000) NULL,
	other_previous_residence_length_of_residency varchar(1000) NULL,
	other_previous_residence_reason_for_leaving varchar(1000) NULL,
	other_previous_residence_rent_amount numeric(30,4) NULL,
	other_previous_residence_rent_own_na varchar(1000) NULL,
	previous_employer_address varchar(1000) NULL,
	previous_employer_name varchar(1000) NULL,
	previous_employment_estimated_annual_income numeric(30,4) NULL,
	previous_employment_job_title varchar(1000) NULL,
	previous_employment_job_type varchar(1000) NULL,
	previous_employment_length_of_employment varchar(1000) NULL,
	previous_residence_address varchar(1000) NULL,
	previous_residence_length_of_residency varchar(1000) NULL,
	previous_residence_reason_for_leaving varchar(1000) NULL,
	previous_residence_rent_amount numeric(30,4) NULL,
	previous_residence_rent_own_na varchar(1000) NULL,
	previous_residence_residence_name varchar(1000) NULL,
	has_been_evicted varchar(1000) NULL,
	has_been_sued_for_property_damages varchar(1000) NULL,
	has_been_sued_for_rent varchar(1000) NULL,
	has_broken_lease varchar(1000) NULL,
	insert_date timestamp DEFAULT now() NOT NULL,
	update_date timestamp DEFAULT now() NOT NULL,
   PRIMARY KEY (resident_member_id, site_id_property_unit_number)
 ) ON COMMIT DROP;


WITH ranked_cld AS (
    SELECT
        cld.*,
        du.property_number,
        ROW_NUMBER() OVER (
            PARTITION BY
                cld.resident_member_id,
                cld.onsiteid || '-' || du.property_number || '-' || cld.unit_number
            ORDER BY
                cld.load_timestamp DESC NULLS LAST
        ) AS rn
    FROM staging.contact_level_details cld
    left JOIN analytics.dim_unit du
        ON du.onsiteid::int = cld.onsiteid
       AND lower(cld.unit_number) = lower(du.unit_number)
--       AND lower(cld.property_name) = lower(du.property_name)
    WHERE COALESCE(lower(cld.unit_number), '') <> 'none'
      AND COALESCE(cld.unit_number, '') <> ''
--      AND cld.screening_current_historical = 'Current'
)

INSERT INTO temp_contact_level_details (
		property_name,
		site_id_property_unit_number,
		resident_member_id,
		current_employment_additional_annual_income,
		current_employment_address,
		current_employment_estimated_annual_income,
		current_employment_job_title,
		current_employment_job_type,
		current_employment_length_of_employment,
		current_employment_miles_to_work,
		current_employment_name,
		current_employment_start_date,
		age,
		citizenship,
		contact_primary_language,
		ethnicity,
		gender,
		marital_status,
		co_signer,
		criminal_history,
		email,
		employee,
		first_name,
		middle_name,
		last_name,
		forwarding_address,
		guarantor,
		home_phone,
		lease_signer,
		length_of_stay,
		occupant,
		opt_in_for_email_notifications,
		relationship_household_status,
		resident_since,
		applied_date,
		contact_level_status,
		custom_payment_plan_name,
		household_language,
		household_name,
		lease_start_date,
		lease_end_date,
		lease_level_occupancy_status,
		ledger_balance,
		payment_plan_name,
		unit_number,
		screening_current_historical,
		screening_decision,
		screening_submission_date,
		screening_decision_by,
		screening_decision_date,
		screening_override_decision,
		screening_override_decision_factors,
		other_previous_residence_address,
		other_previous_residence_length_of_residency,
		other_previous_residence_reason_for_leaving,
		other_previous_residence_rent_amount,
		other_previous_residence_rent_own_na,
		previous_employer_address,
		previous_employer_name,
		previous_employment_estimated_annual_income,
		previous_employment_job_title,
		previous_employment_job_type,
		previous_employment_length_of_employment,
		previous_residence_address,
		previous_residence_length_of_residency,
		previous_residence_reason_for_leaving,
		previous_residence_rent_amount,
		previous_residence_rent_own_na,
		previous_residence_residence_name,
		has_been_evicted,
		has_been_sued_for_property_damages,
		has_been_sued_for_rent,
		has_broken_lease,
		insert_date,
		update_date

    )
    SELECT
		cld.property_name,
		cld.onsiteid || '-' || cld.property_number || '-' || cld.unit_number as site_id_property_unit_number,
        cld.resident_member_id::int,
		cld.current_employment_additional_annual_income,
		cld.current_employment_address,
		NULLIF(REPLACE(cld.current_employment_estimated_annual_income, ',', ''), '')::numeric(30,4) AS current_employment_estimated_annual_income,
		cld.current_employment_job_title,
		cld.current_employment_job_type,
		cld.current_employment_length_of_employment,
		NULLIF(REPLACE(cld.current_employment_miles_to_work, ',', ''), '')::numeric(30,4) AS current_employment_miles_to_work,
		cld.current_employment_name,
		NULLIF(NULLIF(cld.current_employment_start_date, '')::DATE, '1899-12-31'::DATE) AS current_employment_start_date,
		CASE WHEN NULLIF(cld.age, '')::INT BETWEEN 1 AND 100 THEN NULLIF(cld.age, '')::INT ELSE NULL END AS age,
		cld.citizenship,
		cld.contact_primary_language,
		cld.ethnicity,
		cld.gender,
		cld.marital_status,
		cld.co_signer,
		cld.criminal_history,
		cld.email,
		cld.employee,
		cld.first_name,
		cld.middle_name,
		cld.last_name,
		cld.forwarding_address,
		cld.guarantor,
		cld.home_phone,
		cld.lease_signer,
		cld.length_of_stay,
		cld.occupant,
		cld.opt_in_for_email_notifications,
		cld.relationship_household_status,
		NULLIF(NULLIF(cld.resident_since, '')::DATE, '1899-12-31'::DATE) AS resident_since,
		NULLIF(NULLIF(cld.applied_date, '')::DATE, '1899-12-31'::DATE) AS applied_date,
		cld.contact_level_status,
		cld.custom_payment_plan_name,
		cld.household_language,
		cld.household_name,
		NULLIF(NULLIF(cld.lease_start_date, '')::DATE, '1899-12-31'::DATE) AS lease_start_date,
		NULLIF(NULLIF(cld.lease_end_date, '')::DATE, '1899-12-31'::DATE) AS lease_end_date,
		cld.lease_level_occupancy_status,
		NULLIF(REPLACE(cld.ledger_balance, ',', ''), '')::numeric(30,4) AS ledger_balance,
		cld.payment_plan_name,
		cld.unit_number,
		cld.screening_current_historical,
		cld.screening_decision,
		NULLIF(NULLIF(cld.screening_submission_date, '')::DATE, '1899-12-31'::DATE) AS screening_submission_date,
		cld.screening_decision_by,
		NULLIF(NULLIF(cld.screening_decision_date, '')::DATE, '1899-12-31'::DATE) AS screening_decision_date,
		cld.screening_override_decision,
		cld.screening_override_decision_factors,
		cld.other_previous_residence_address,
		cld.other_previous_residence_length_of_residency,
		cld.other_previous_residence_reason_for_leaving,
		NULLIF(REPLACE(cld.other_previous_residence_rent_amount, ',', ''), '')::numeric(30,4) AS other_previous_residence_rent_amount,
		cld.other_previous_residence_rent_own_na,
		cld.previous_employer_address,
		cld.previous_employer_name,
		NULLIF(REPLACE(cld.previous_employment_estimated_annual_income, ',', ''), '')::numeric(30,4) AS previous_employment_estimated_annual_income,
		cld.previous_employment_job_title,
		cld.previous_employment_job_type,
		cld.previous_employment_length_of_employment,
		cld.previous_residence_address,
		cld.previous_residence_length_of_residency,
		cld.previous_residence_reason_for_leaving,
		NULLIF(REPLACE(cld.previous_residence_rent_amount, ',', ''), '')::numeric(30,4) AS previous_residence_rent_amount,
		cld.previous_residence_rent_own_na,
		cld.previous_residence_residence_name,
		cld.has_been_evicted,
		cld.has_been_sued_for_property_damages,
		cld.has_been_sued_for_rent,
		cld.has_broken_lease,
		NOW() AS insert_date,
		NOW() AS update_date
    FROM ranked_cld AS cld
	WHERE rn = 1;

MERGE INTO analytics.dim_contact_level_details AS cld
USING temp_contact_level_details AS tcld
ON cld.resident_member_id::int = tcld.resident_member_id::int and
cld.site_id_property_unit_number=tcld.site_id_property_unit_number
WHEN MATCHED THEN
    UPDATE SET
current_employment_additional_annual_income = tcld.current_employment_additional_annual_income,
current_employment_address = tcld.current_employment_address,
current_employment_estimated_annual_income = tcld.current_employment_estimated_annual_income,
current_employment_job_title = tcld.current_employment_job_title,
current_employment_job_type = tcld.current_employment_job_type,
current_employment_length_of_employment = tcld.current_employment_length_of_employment,
current_employment_miles_to_work = tcld.current_employment_miles_to_work,
current_employment_name = tcld.current_employment_name,
current_employment_start_date = tcld.current_employment_start_date,
age = tcld.age,
citizenship = tcld.citizenship,
contact_primary_language = tcld.contact_primary_language,
ethnicity = tcld.ethnicity,
gender = tcld.gender,
marital_status = tcld.marital_status,
co_signer = tcld.co_signer,
criminal_history = tcld.criminal_history,
email = tcld.email,
employee = tcld.employee,
first_name = tcld.first_name,
middle_name = tcld.middle_name,
last_name = tcld.last_name,
forwarding_address = tcld.forwarding_address,
guarantor = tcld.guarantor,
home_phone = tcld.home_phone,
lease_signer = tcld.lease_signer,
length_of_stay = tcld.length_of_stay,
occupant = tcld.occupant,
opt_in_for_email_notifications = tcld.opt_in_for_email_notifications,
relationship_household_status = tcld.relationship_household_status,
resident_since = tcld.resident_since,
applied_date = tcld.applied_date,
contact_level_status = tcld.contact_level_status,
custom_payment_plan_name = tcld.custom_payment_plan_name,
household_language = tcld.household_language,
household_name = tcld.household_name,
lease_start_date = tcld.lease_start_date,
lease_end_date = tcld.lease_end_date,
lease_level_occupancy_status = tcld.lease_level_occupancy_status,
ledger_balance = tcld.ledger_balance,
payment_plan_name = tcld.payment_plan_name,
unit_number = tcld.unit_number,
screening_current_historical = tcld.screening_current_historical,
screening_decision = tcld.screening_decision,
screening_submission_date = tcld.screening_submission_date,
screening_decision_by = tcld.screening_decision_by,
screening_decision_date = tcld.screening_decision_date,
screening_override_decision = tcld.screening_override_decision,
screening_override_decision_factors = tcld.screening_override_decision_factors,
other_previous_residence_address = tcld.other_previous_residence_address,
other_previous_residence_length_of_residency = tcld.other_previous_residence_length_of_residency,
other_previous_residence_reason_for_leaving = tcld.other_previous_residence_reason_for_leaving,
other_previous_residence_rent_amount = tcld.other_previous_residence_rent_amount,
other_previous_residence_rent_own_na = tcld.other_previous_residence_rent_own_na,
previous_employer_address = tcld.previous_employer_address,
previous_employer_name = tcld.previous_employer_name,
previous_employment_estimated_annual_income = tcld.previous_employment_estimated_annual_income,
previous_employment_job_title = tcld.previous_employment_job_title,
previous_employment_job_type = tcld.previous_employment_job_type,
previous_employment_length_of_employment = tcld.previous_employment_length_of_employment,
previous_residence_address = tcld.previous_residence_address,
previous_residence_length_of_residency = tcld.previous_residence_length_of_residency,
previous_residence_reason_for_leaving = tcld.previous_residence_reason_for_leaving,
previous_residence_rent_amount = tcld.previous_residence_rent_amount,
previous_residence_rent_own_na = tcld.previous_residence_rent_own_na,
previous_residence_residence_name = tcld.previous_residence_residence_name,
has_been_evicted = tcld.has_been_evicted,
has_been_sued_for_property_damages = tcld.has_been_sued_for_property_damages,
has_been_sued_for_rent = tcld.has_been_sued_for_rent,
has_broken_lease = tcld.has_broken_lease,
update_date=tcld.update_date

WHEN NOT MATCHED THEN
    INSERT (property_name,
			site_id_property_unit_number,
			resident_member_id,
			current_employment_additional_annual_income,
			current_employment_address,
			current_employment_estimated_annual_income,
			current_employment_job_title,
			current_employment_job_type,
			current_employment_length_of_employment,
			current_employment_miles_to_work,
			current_employment_name,
			current_employment_start_date,
			age,
			citizenship,
			contact_primary_language,
			ethnicity,
			gender,
			marital_status,
			co_signer,
			criminal_history,
			email,
			employee,
			first_name,
			middle_name,
			last_name,
			forwarding_address,
			guarantor,
			home_phone,
			lease_signer,
			length_of_stay,
			occupant,
			opt_in_for_email_notifications,
			relationship_household_status,
			resident_since,
			applied_date,
			contact_level_status,
			custom_payment_plan_name,
			household_language,
			household_name,
			lease_start_date,
			lease_end_date,
			lease_level_occupancy_status,
			ledger_balance,
			payment_plan_name,
			unit_number,
			screening_current_historical,
			screening_decision,
			screening_submission_date,
			screening_decision_by,
			screening_decision_date,
			screening_override_decision,
			screening_override_decision_factors,
			other_previous_residence_address,
			other_previous_residence_length_of_residency,
			other_previous_residence_reason_for_leaving,
			other_previous_residence_rent_amount,
			other_previous_residence_rent_own_na,
			previous_employer_address,
			previous_employer_name,
			previous_employment_estimated_annual_income,
			previous_employment_job_title,
			previous_employment_job_type,
			previous_employment_length_of_employment,
			previous_residence_address,
			previous_residence_length_of_residency,
			previous_residence_reason_for_leaving,
			previous_residence_rent_amount,
			previous_residence_rent_own_na,
			previous_residence_residence_name,
			has_been_evicted,
			has_been_sued_for_property_damages,
			has_been_sued_for_rent,
			has_broken_lease,
			insert_date,
			update_date
			)
    VALUES (
			tcld.property_name,
			tcld.site_id_property_unit_number,
			tcld.resident_member_id::int,
			tcld.current_employment_additional_annual_income,
			tcld.current_employment_address,
			tcld.current_employment_estimated_annual_income,
			tcld.current_employment_job_title,
			tcld.current_employment_job_type,
			tcld.current_employment_length_of_employment,
			tcld.current_employment_miles_to_work,
			tcld.current_employment_name,
			tcld.current_employment_start_date,
			tcld.age,
			tcld.citizenship,
			tcld.contact_primary_language,
			tcld.ethnicity,
			tcld.gender,
			tcld.marital_status,
			tcld.co_signer,
			tcld.criminal_history,
			tcld.email,
			tcld.employee,
			tcld.first_name,
			tcld.middle_name,
			tcld.last_name,
			tcld.forwarding_address,
			tcld.guarantor,
			tcld.home_phone,
			tcld.lease_signer,
			tcld.length_of_stay,
			tcld.occupant,
			tcld.opt_in_for_email_notifications,
			tcld.relationship_household_status,
			tcld.resident_since,
			tcld.applied_date,
			tcld.contact_level_status,
			tcld.custom_payment_plan_name,
			tcld.household_language,
			tcld.household_name,
			tcld.lease_start_date,
			tcld.lease_end_date,
			tcld.lease_level_occupancy_status,
			tcld.ledger_balance,
			tcld.payment_plan_name,
			tcld.unit_number,
			tcld.screening_current_historical,
			tcld.screening_decision,
			tcld.screening_submission_date,
			tcld.screening_decision_by,
			tcld.screening_decision_date,
			tcld.screening_override_decision,
			tcld.screening_override_decision_factors,
			tcld.other_previous_residence_address,
			tcld.other_previous_residence_length_of_residency,
			tcld.other_previous_residence_reason_for_leaving,
			tcld.other_previous_residence_rent_amount,
			tcld.other_previous_residence_rent_own_na,
			tcld.previous_employer_address,
			tcld.previous_employer_name,
			tcld.previous_employment_estimated_annual_income,
			tcld.previous_employment_job_title,
			tcld.previous_employment_job_type,
			tcld.previous_employment_length_of_employment,
			tcld.previous_residence_address,
			tcld.previous_residence_length_of_residency,
			tcld.previous_residence_reason_for_leaving,
			tcld.previous_residence_rent_amount,
			tcld.previous_residence_rent_own_na,
			tcld.previous_residence_residence_name,
			tcld.has_been_evicted,
			tcld.has_been_sued_for_property_damages,
			tcld.has_been_sued_for_rent,
			tcld.has_broken_lease,
			tcld.insert_date,
			tcld.update_date
			);

END;
$procedure$
;
