
SCHEMA={
    "Resident Member ID": "resident_member_id",
    "Current Employment Additional Annual Income": "current_employment_additional_annual_income",
    "Current Employment Address": "current_employment_address",
    "Current Employment Estimated Annual Income": "current_employment_estimated_annual_income",
    "Current Employment Job Title": "current_employment_job_title",
    "Current Employment Job Type": "current_employment_job_type",
    "Current Employment Length of Employment": "current_employment_length_of_employment",
    "Current Employment Miles to Work": "current_employment_miles_to_work",
    "Current Employment Name": "current_employment_name",
    "Current Employment Start Date": "current_employment_start_date",
    "Age": "age",
    "Citizenship": "citizenship",
    "Contact Primary Language": "contact_primary_language",
    "Ethnicity": "ethnicity",
    "Gender": "gender",
    "Marital Status": "marital_status",
    "Co-signer": "co_signer",
    "Criminal History": "criminal_history",
    "E-mail": "email",
    "Employee": "employee",
    "First Name": "first_name",
    "Middle Name": "middle_name",
    "Last Name": "last_name",
    "Forwarding Address": "forwarding_address",
    "Guarantor": "guarantor",
    "Home Phone": "home_phone",
    "Lease Signer": "lease_signer",
    "Length of Stay": "length_of_stay",
    "Occupant": "occupant",
    "Opt In for E-mail Notifications": "opt_in_for_email_notifications",
    "Relationship (Household Status)": "relationship_household_status",
    "Resident Since": "resident_since",
    "Applied Date": "applied_date",
    "Contact-level Status": "contact_level_status",
    "Custom Payment Plan Name": "custom_payment_plan_name",
    "Household Language": "household_language",
    "Household Name": "household_name",
    "Lease Start Date": "lease_start_date",
    "Lease End Date": "lease_end_date",
    "Lease-level Occupancy Status": "lease_level_occupancy_status",
    "Ledger Balance": "ledger_balance",
    "Payment Plan Name": "payment_plan_name",
    "Unit #": "unit_number",
    "Screening Current/Historical": "screening_current_historical",
    "Screening Decision": "screening_decision",
    "Screening Submission Date": "screening_submission_date",
    "Screening Decision By": "screening_decision_by",
    "Screening Decision Date": "screening_decision_date",
    "Screening Override Decision": "screening_override_decision",
    "Screening Override Decision Factors": "screening_override_decision_factors",
    "Other Previous Residence Address": "other_previous_residence_address",
    "Other Previous Residence Length of Residency": "other_previous_residence_length_of_residency",
    "Other Previous Residence Reason for Leaving": "other_previous_residence_reason_for_leaving",
    "Other Previous Residence Rent Amount": "other_previous_residence_rent_amount",
    "Other Previous Residence Rent/Own/N/A": "other_previous_residence_rent_own_na",
    "Previous Employer Address": "previous_employer_address",
    "Previous Employer Name": "previous_employer_name",
    "Previous Employment Estimated Annual Income": "previous_employment_estimated_annual_income",
    "Previous Employment Job Title": "previous_employment_job_title",
    "Previous Employment Job Type": "previous_employment_job_type",
    "Previous Employment Length of Employment": "previous_employment_length_of_employment",
    "Previous Residence Address": "previous_residence_address",
    "Previous Residence Length of Residency": "previous_residence_length_of_residency",
    "Previous Residence Reason for Leaving": "previous_residence_reason_for_leaving",
    "Previous Residence Rent Amount": "previous_residence_rent_amount",
    "Previous Residence Rent/Own/N/A": "previous_residence_rent_own_na",
    "Previous Residence Residence Name": "previous_residence_residence_name",
    "Has been evicted?": "has_been_evicted",
    "Has been sued for property damages?": "has_been_sued_for_property_damages",
    "Has been sued for rent?": "has_been_sued_for_rent",
    "Has broken lease?": "has_broken_lease"
}

CARD_TRANSACTIONS_SCHEMA = { "Transaction ID": "transaction_id",
    "Transaction Date": "transaction_date",
    "Post Date": "post_date",
    "Transaction Amount": "transaction_amount",
    "Merchant Surcharge": "merchant_surcharge",
    "Account Number": "account_number",
    "Cardholder Last Name": "cardholder_last_name",
    "Cardholder First Name": "cardholder_first_name",
    "Cardholder Middle Initial": "cardholder_middle_initial",
    "Central Bill Account": "central_bill_account",
    "Billed To Account": "billed_to_account",
    "Diversion Account": "diversion_account",
    "Parent Merchant Name": "parent_merchant_name",
    "Merchant Name": "merchant_name",
    "Original Merchant Name": "original_merchant_name",
    "MCC": "mcc",
    "MCC Description": "mcc_description",
    "Merchant Type": "merchant_type",
    "Merchant Address 1": "merchant_address_1",
    "Merchant Address 2": "merchant_address_2",
    "Merchant City": "merchant_city",
    "Merchant State/Province": "merchant_state_province",
    "Merchant Country": "merchant_country",
    "Merchant Postal Code": "merchant_postal_code",
    "Transaction Code": "transaction_code",
    "Transaction Code Reason Code": "transaction_code_reason_code",
    "Sales Tax": "sales_tax",
    "Settled Currency": "settled_currency",
    "Original Currency": "original_currency",
    "Original Amount": "original_amount",
    "Exchange Rate": "exchange_rate",
    "Item Description": "item_description",
    "Item Unit Price Amount": "item_unit_price_amount",
    "Item Quantity": "item_quantity",
    "Item Detail Tax Amount": "item_detail_tax_amount",
    "Line Item Total": "line_item_total",
    "Chart of Accounts": "chart_of_accounts",
    "1099 Indicator": "indicator_1099",
    "Socio-Economic Indicator 1": "socio_economic_indicator_1",
    "Socio-Economic Indicator 2": "socio_economic_indicator_2",
    "Transaction Item COA Segment Value 1": "coa_segment_value_1",
    "Transaction Item COA Segment Value 2": "coa_segment_value_2",
    "Transaction Item COA Segment Value 3": "coa_segment_value_3",
    "Transaction Item COA Segment Value 4": "coa_segment_value_4",
    "Transaction Item COA Segment Value 5": "coa_segment_value_5",
    "Transaction Item COA Segment Value 6": "coa_segment_value_6",
    "Transaction Item COA Segment Value 7": "coa_segment_value_7",
    "Transaction Item COA Segment Value  8": "coa_segment_value_8",
    "Transaction Item COA Segment Value 9": "coa_segment_value_9",
    "Transaction Item COA Segment Value 10": "coa_segment_value_10",

    "Hierarchy ID": "hierarchy_id",
    "Hierarchy Description": "hierarchy_description",

    "Reference Number": "reference_number",
    "Transaction Convenience Check Number": "transaction_convenience_check_number",
    "Transaction Authorization Number": "transaction_authorization_number",

    "Customer Code": "customer_code",
    "Transaction Type": "transaction_type",

    "Dispute Indicator": "dispute_indicator",
    "Dispute Status": "dispute_status",

    "Transaction Export Status Code": "transaction_export_status_code",
    "Transaction Approval Status": "transaction_approval_status",

    "Approval Indicator 1": "approval_indicator_1",
    "Transaction Approver Name 1": "transaction_approver_name_1",
    "Approval Indicator 2": "approval_indicator_2",
    "Transaction Approver Name 2": "transaction_approver_name_2",
    "Approval Indicator 3": "approval_indicator_3",
    "Transaction Approver Name 3": "transaction_approver_name_3",
    "Approval Indicator 4": "approval_indicator_4",
    "Transaction Approver Name 4": "transaction_approver_name_4",
    "Approval Indicator 5": "approval_indicator_5",
    "Transaction Approver Name 5": "transaction_approver_name_5",

    "Custom Field Value 1": "custom_field_value_1",
    "Custom Field Value 2": "custom_field_value_2",
    "Custom Field Value 3": "custom_field_value_3",
    "Custom Field Value 4": "custom_field_value_4",
    "Custom Field Value 5": "custom_field_value_5",
    "Custom Field Value 6": "custom_field_value_6",
    "Custom Field Value 7": "custom_field_value_7",
    "Custom Field Value 8": "custom_field_value_8",
    "Custom Field Value 9": "custom_field_value_9",
    "Custom Field Value 10": "custom_field_value_10",

    "Transaction Notes": "transaction_notes",
    "Order ID": "order_id",
    "Order Status": "order_status",
    "Requestor": "requestor"
}
